### PR TITLE
Add MDC context to Raygun custom data

### PR DESCRIPTION
**Pull request by ajmath**
We use the logging mdc context to inject per-request data via jersey filters.  This is making it out to our logging stack but missing from Raygun and not possible without re-implementing the appender.  This PR will automatically include anything in the mdc context in the Raygun custom data with the "mdc:" prefix for the key.

### CODE REVIEW

**Comment by gkopff** [comment]
Thanks. I'll get a new version out shortly.  Do you have any other improvements before I do so?

**Comment by ajmath** [comment]
Nope, this was the only one we needed.  Thanks

**Comment by gkopff** [comment]
That's been released as `1.4.0` and should show up in Maven Central "soon".

**Comment by gkopff** [comment]
Thanks for the contribution!

**Pull request merged**
