### PR TITLE
Add support for specifying tags

### PR DESCRIPTION
**Pull request by connec**
This required updating the raygun dependency (`com.mindscapehq:core`) to the latest version (`2.0.0`).

I used an immutable list for the tags, though I'm not sure if it's really necessary.

### CODE REVIEW

**Comment by gkopff** [comment]
Do you have an example of the tags to update the README with?

**Comment by connec** [comment]
I'll whip one up soon and add it to the PR.

**Comment by connec** [comment]
Voila.  How's that?

**Comment by gkopff** [comment]
Great thanks.

Is anything else coming down the pipeline?

**Comment by connec** [comment]
Nope, I think that's it from me.  Thanks for the amazing responsiveness! :)

**Comment by gkopff** [comment]
Thanks for the contributions!

**Comment by gkopff** [comment]
This has been published as `1.3.0` and should be Maven central shortly.

**Pull request merged**
